# Generated by Django 4.2.5 on 2023-09-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('event_type', models.CharField(choices=[('Birthday', 'Birthday'), ('Work Anniversaries', 'Work Anniversaries.')], max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
