# Generated by Django 4.2.5 on 2023-09-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='date',
            new_name='event_date',
        ),
    ]
